Build libmod_pagespeed.so (#3)
Some tweaks/changes to produce `libmod_pagespeed.so`
Manually tested to work with apache 2.4 

- Add target for libmod_pagespeed.so
- Fixes for building the shared library
- Hack to avoid undefined reference to base::NumberToString
  in code we don't use
-  Add -DPAGESPEED_SUPPORT_POSIX_SHARED_MEM=1